-- infrastructure/database/seeders/institutions_seed.sql

-- Clear existing data (optional - comment out if you want to keep existing data)
-- DELETE FROM institutions;

-- Insert institution data
INSERT INTO institutions (
    id,
    code,
    name,
    type,
    country,
    description,
    founding_date,
    number_of_employees,
    number_of_students,
    legal_name,
    logo,
    parent_organization,
    website,
    email,
    phone,
    address,
    vfee,
    process,
    processing_time,
    api_endpoint,
    api_key,
    is_active,
    created_at,
    updated_at
) VALUES
(
    gen_random_uuid(),
    'UG',
    'University of Ghana',
    'University',
    'Ghana',
    'The premier university in Ghana, founded as the University College of the Gold Coast by Ordinance on August 11, 1948 for the purpose of providing and promoting university education, learning and research. The university aims to become a world-class research-intensive institution.',
    '1948',
    6565,
    65000,
    'University of Ghana',
    'https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/University_of_Ghana_seal.svg/300px-University_of_Ghana_seal.svg.png',
    NULL,
    'https://www.ug.edu.gh',
    'admissions@ug.edu.gh',
    '+233 30 253 6883',
    'P.O. Box LG 25, Legon, Accra, Ghana',
    15.00,
    'manual',
    '10 days',
    '',
    '',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'KNUST',
    'Kwame Nkrumah University of Science and Technology',
    'University',
    'Ghana',
    'A university in Kumasi, Ghana, focused on science and technology. It was founded in 1952 as Kumasi College of Technology and renamed in 1961 after Ghana''s first president, Kwame Nkrumah. KNUST is known for its strong engineering, science, and technology programs.',
    '1952',
    7200,
    85000,
    'Kwame Nkrumah University of Science and Technology',
    'https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Kwame_Nkrumah_University_of_Science_and_Technology_seal.svg/300px-Kwame_Nkrumah_University_of_Science_and_Technology_seal.svg.png',
    NULL,
    'https://www.knust.edu.gh',
    'admissions@knust.edu.gh',
    '+233 3220 60021',
    'Private Mail Bag, University Post Office, Kumasi, Ghana',
    15.00,
    'manual',
    '10 days',
    '',
    '',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'UCC',
    'University of Cape Coast',
    'University',
    'Ghana',
    'A public university located in Cape Coast, Ghana. It was established in 1962 out of a dire need for highly qualified and skilled manpower in education and is ranked among the top universities in Ghana and Africa for education and research.',
    '1962',
    4500,
    75000,
    'University of Cape Coast',
    'https://upload.wikimedia.org/wikipedia/en/thumb/9/95/University_of_Cape_Coast_logo.svg/300px-University_of_Cape_Coast_logo.svg.png',
    NULL,
    'https://www.ucc.edu.gh',
    'info@ucc.edu.gh',
    '+233 3321 32480',
    'University Post Office, Cape Coast, Ghana',
    15.00,
    'manual',
    '10 days',
    '',
    '',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'UEW',
    'University of Education, Winneba',
    'University',
    'Ghana',
    'A public university in Winneba, Ghana, established in 1992. It specializes in teacher education and offers programs in education, business, science, and arts. UEW is dedicated to producing quality teachers and educational professionals for Ghana and beyond.',
    '1992',
    3800,
    82000,
    'University of Education, Winneba',
    'https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/University_of_Education%2C_Winneba_logo.svg/300px-University_of_Education%2C_Winneba_logo.svg.png',
    NULL,
    'https://www.uew.edu.gh',
    'info@uew.edu.gh',
    '+233 2333 221 611',
    'P.O. Box 25, Winneba, Ghana',
    15.00,
    'manual',
    '10 days',
    '',
    '',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'UMaT',
    'University of Mines and Technology',
    'University',
    'Ghana',
    'A public university located in Tarkwa, Ghana, established in 2004. Formerly known as the Tarkwa School of Mines, UMaT specializes in mining, petroleum, and engineering education. It is recognized for producing skilled professionals for Ghana''s mining and petroleum industries.',
    '2004',
    1200,
    8500,
    'University of Mines and Technology',
    'https://upload.wikimedia.org/wikipedia/en/thumb/5/5a/University_of_Mines_and_Technology_logo.svg/300px-University_of_Mines_and_Technology_logo.svg.png',
    NULL,
    'https://umat.edu.gh',
    'admissions@umat.edu.gh',
    '+233 3123 20324',
    'P.O. Box 237, Tarkwa, Ghana',
    15.00,
    'manual',
    '10 days',
    '',
    '',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'UPSA',
    'University of Professional Studies, Accra',
    'University',
    'Ghana',
    'A public university in Accra, Ghana, specializing in business education. Originally established in 1965 as a professional business school, it gained full university status in 2012. UPSA is known for its strong business, accounting, and marketing programs.',
    '1965',
    2500,
    18000,
    'University of Professional Studies, Accra',
    'https://upload.wikimedia.org/wikipedia/en/thumb/e/e3/University_of_Professional_Studies_Accra_logo.svg/300px-University_of_Professional_Studies_Accra_logo.svg.png',
    NULL,
    'https://upsa.edu.gh',
    'admissions@upsa.edu.gh',
    '+233 302 500 171',
    'P.O. Box LG 149, Accra, Ghana',
    15.00,
    'manual',
    '10 days',
    '',
    '',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'GIMPA',
    'Ghana Institute of Management and Public Administration',
    'University',
    'Ghana',
    'A public university in Accra, Ghana, established in 1961. Originally focused on training public administrators, GIMPA has expanded to offer programs in business, law, technology, and leadership development for both public and private sectors.',
    '1961',
    1800,
    15000,
    'Ghana Institute of Management and Public Administration',
    'https://upload.wikimedia.org/wikipedia/en/thumb/6/6f/GIMPA_logo.svg/300px-GIMPA_logo.svg.png',
    NULL,
    'https://www.gimpa.edu.gh',
    'admissions@gimpa.edu.gh',
    '+233 302 401 681',
    'P.O. Box AH 50, Achimota, Accra, Ghana',
    15.00,
    'manual',
    '10 days',
    '',
    '',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'UHAS',
    'University of Health and Allied Sciences',
    'University',
    'Ghana',
    'A public university established in 2011 with campuses in Ho and Hohoe, Ghana. UHAS focuses on health sciences education and research, offering programs in medicine, nursing, pharmacy, public health, and allied health sciences.',
    '2011',
    2100,
    12000,
    'University of Health and Allied Sciences',
    'https://upload.wikimedia.org/wikipedia/en/thumb/0/06/University_of_Health_and_Allied_Sciences_logo.svg/300px-University_of_Health_and_Allied_Sciences_logo.svg.png',
    NULL,
    'https://www.uhas.edu.gh',
    'registrar@uhas.edu.gh',
    '+233 3620 26498',
    'PMB 31, Ho, Volta Region, Ghana',
    15.00,
    'manual',
    '10 days',
    '',
    '',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'UENR',
    'University of Energy and Natural Resources',
    'University',
    'Ghana',
    'A public university established in 2011 in Sunyani, Ghana, focusing on energy and natural resources management. UENR offers programs in renewable energy, environmental science, agriculture, and natural resources management to support sustainable development.',
    '2011',
    1600,
    9000,
    'University of Energy and Natural Resources',
    'https://upload.wikimedia.org/wikipedia/en/thumb/2/2f/UENR_logo.svg/300px-UENR_logo.svg.png',
    NULL,
    'https://www.uenr.edu.gh',
    'admissions@uenr.edu.gh',
    '+233 3520 92352',
    'P.O. Box 214, Sunyani, Ghana',
    15.00,
    'manual',
    '10 days',
    '',
    '',
    true,
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'GCTU',
    'Ghana Communication Technology University',
    'University',
    'Ghana',
    'A public university in Accra, Ghana, specializing in information technology and communications. Formerly known as Ghana Telecom University College, it was established in 2005 and focuses on ICT, engineering, business, and technology management.',
    '2005',
    1400,
    11000,
    'Ghana Communication Technology University',
    'https://upload.wikimedia.org/wikipedia/en/thumb/1/15/Ghana_Communication_Technology_University_logo.svg/300px-Ghana_Communication_Technology_University_logo.svg.png',
    NULL,
    'https://www.gctu.edu.gh',
    'info@gctu.edu.gh',
    '+233 302 221 213',
    'PMB 100, Tesano, Accra, Ghana',
    15.00,
    'manual',
    '10 days',
    '',
    '',
    true,
    NOW(),
    NOW()
);

-- Output success message
SELECT '✅ Successfully seeded 10 institutions' AS message;